### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by ffMathy** [xtermi2/elasticsearch-searchguard#6]
Finally got around to try this in the weekend.

However, I am getting the following error from within the container.

> Unable to read /usr/share/elasticsearch/config/node.pem (/usr/share/elasticsearch/config/node.pem). Please make sure this files 
exists and is readable regarding to permissions

I am running it from a folder where there is a `certs` folder, with the given file in. The `docker-compose.yml` file mounts that to the correct path. Here is the relevant part of my `docker-compose.yml` file's volumes:

```
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certificates
```

However, if I SSH into the container running `elasticsearch`, I can't go to the given directory. In fact, there isn't even an `elasticsearch` folder in `/usr/share`.

Any ideas what I am doing wrong?

I already made sure that the given paths were present on the host machine.

**Comment by xtermi2** [comment]
I don't know some important parts:

- which operating system are you using?
- which version of the image are you using?
- I don't know your docker-compose.yml

So I tried do give you a step-by-step manual to get the example working. I Use linux, for windows you have to adapt the steps. On macOS this should work more or less the same way, but I can't guarantee this.
```bash
git clone git@github.com:xtermi2/elasticsearch-searchguard.git
cd elasticsearch-searchguard/example/

# now I follow the instructions on https://github.com/xtermi2/elasticsearch-searchguard/tree/master/example
wget "https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-tlstool/1.7/search-guard-tlstool-1.7.zip" -O search-guard-tlstool.zip
unzip search-guard-tlstool.zip
rm -rf out && ./tools/sgtlstool.sh -c tls-tool_certificate_config.yml -ca -crt
sudo sysctl -w vm.max_map_count=262144

# it's important to have more than 15% percent free disk space on your root fileystem (or where docker is installed) 
# because Elasticsearch has differnet watermarks wo prevent 100% filled disks and the lowest is at 85% disk usage

docker-compose up

# after some time all applications including Elasticsearch are up

curl -k -u 'elastic:elastic' "https://localhost:9200/_cluster/health?pretty"
```
This works fine for me. Can you reproduce this example working?


This means I can't reproduce your file not found issue. 
Maybe it's just a permission issue:
```bash
chmod -R 777 certs
```

**The other option is to use the test docker-compose.yml:**

```bash
git clone git@github.com:xtermi2/elasticsearch-searchguard.git
cd elasticsearch-searchguard/src/test

sudo sysctl -w vm.max_map_count=262144

# it's important to have more than 15% percent free disk space on your root fileystem (or where docker is installed) 
# because Elasticsearch has differnet watermarks wo prevent 100% filled disks and the lowest is at 85% disk usage

# this docker-compose.yml could be fragile, because it uses no tag and after a 6.x release the latest tag points to 
# the 6.x image and the rest of the checked out files are on master branch and don't fit.
# To fix this you should replace 'xtermi2/elasticsearch-searchguard' with 'xtermi2/elasticsearch-searchguard:7.6.0' 
# which is currently the latest version:
sed -i -e 's/xtermi2\/elasticsearch-searchguard/xtermi2\/elasticsearch-searchguard:7.6.0/g' docker-compose.yml

docker-compose up

# after some time all applications including Elasticsearch are up

curl -k -u 'elastic:elastic' "https://localhost:9200/_cluster/health?pretty"
```

I hope this will help you somehow.

**Comment by ffMathy** [comment]
- Operating system: `Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1021-aws x86_64)`
- Version of image: Latest as of writing

Here's my full `docker-compose.yml` file:

```yaml
version: '3.4'

services:
  dogger:
    image: <omitted>
    restart: always
    env_file:
     - ./env/dogger.env
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - "elasticsearch"
     - "kibana"

  elasticsearch:
    image: xtermi2/elasticsearch-searchguard:7.6.0
    container_name: elasticsearch
    restart: always
    env_file:
     - ./env/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certificates
    ports:
      - "9200:9200"
    restart: always
    healthcheck:
      test: curl -X GET -f -k -u 'elastic:elastic' https://localhost:9200 || exit 1
      interval: 30s
      timeout: 5s
      retries: 10

  kibana:
    image: xtermi2/kibana-searchguard:7.6.0
    container_name: kibana
    env_file:
     - ./env/kibana.env
    ports:
      - "5601:5601"
    restart: always
    healthcheck:
      test: curl -X GET -f http://localhost:5601/status || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
    depends_on:
      - "elasticsearch"
```

As for the `certs` folder, I already ran that command with no luck. Is there anything I can do to verify the permissions in `certs`? I am a Windows guy unfortunately, so I'm a noob when it comes to bash etc.
